namespace AskDelphi.EditingAPI.DTO.ContactListDTOs.Responses
{
    /// <summary>
    /// Response object generated by deleting contact list member endpoint
    /// </summary>
    public class DeleteContactListMemberResponse
    {
    }
}
